name: Build
run-name: Build
on:
  schedule:
    - cron: 0 4 * * *

jobs:
  build:
    name: Generate Build Artifacts
    strategy:
      fail-fast: true
      matrix:
        os: [windows, linux]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Set-up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: '12.16'
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
        run: buildall.bat
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: dist/${{ matrix.os }}
